export const dummy = [
  {
    id: 0,
    src: "/images/img0.jpg",
    catname: "Music",
    eventname: "Musical Night",
    location: "Ludhana",
    ticketprice: 500,
    ticketsize: 100, // for total no. of people
    likes: 0,
    description: "Dj Night with Radio Mirch Rj's",
    organiser: "Shivam",
    date: "08/01/2024",
    time: "8:00 PM",
  },
  {
    id: 1,
    src: "/images/img1.jpg",
    catname: "College",
    eventname: "International Conference on AI",
    location: "Chandigarh",
    ticketprice: 200,
    ticketsize: 250, // for total no. of people
    likes: 0,
    description: "Discussion on the future of AI",
    organiser: "CGC",
    date: "07/07/2024",
    time: "10:00 AM",
  },
  {
    id: 2,
    src: "/images/img2.jpg",
    catname: "Music",
    eventname: "Musi Beats",
    location: "Chandigarh",
    ticketprice: 200,
    ticketsize: 1000, // for total no. of people
    likes: 0,
    description: "A Star Stud night with Super Star Singers",
    organiser: "Chandigarh University",
    date: "04/11/2024",
    time: "7:00 PM",
  },
  {
    id: 3,
    src: "/images/img3.jpg",
    catname: "Business",
    eventname: "Meet and Greet",
    location: "Chandigarh",
    ticketprice: 200,
    ticketsize: 50, // for total no. of people
    likes: 0,
    description: "Meet the business tycons in IT Industry",
    organiser: "Amazon",
    date: "05/12/2024",
    time: "2:00 PM",
  },
  {
    id: 4,
    src: "/images/img4.jpg",
    catname: "Music",
    eventname: "Musical Concert",
    location: "Amritsar",
    ticketprice: 500,
    ticketsize: 5000, // for total no. of people
    likes: 0,
    description: "A Grand Music Concert by Diljit Doshanj",
    organiser: "GNDU",
    date: "05/15/2024",
    time: "9:00 PM",
  },
  {
    id: 5,
    src: "/images/img5.jpg",
    catname: "Business",
    eventname: "Meeting with Foreign Clients",
    location: "Delhi",
    ticketprice: 800,
    ticketsize: 450, // for total no. of people
    likes: 0,
    description: "Meeting our clients and getting to know them better",
    organiser: "IT Tech",
    date: "06/10/2024",
    time: "5:00 PM",
  },
  {
    id: 6,
    src: "/images/img6.jpg",
    catname: "College",
    eventname: "Cultural Fest",
    location: "Amritsar",
    ticketprice: 50,
    ticketsize: 1000, // for total no. of people
    likes: 0,
    description: "A fest to get closer to our culture, explore it and enjoy it",
    organiser: "Chitkara University",
    date: "04/21/2024",
    time: "4:00 PM",
  },
  {
    id: 7,
    src: "/images/img7.jpg",
    catname: "College",
    eventname: "Youth Fest",
    location: "Delhi",
    ticketprice: 300,
    ticketsize: 2000, // for total no. of people
    likes: 0,
    description:
      "A Place to showcase your talent and enjoy fun activities and events",
    organiser: "DU",
    date: "06/27/2024",
    time: "9:00 AM",
  },
  {
    id: 8,
    src: "http://dummyimage.com/238x100.png/dddddd/000000",
    catname: "College",
    eventname: "Tagfeed",
    location: "Delhi",
    ticketprice: "7591",
    ticketsize: "9949",
    likes: "263",
    description:
      "cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices",
    organiser: "Rosenbaum LLC",
    date: "06/27/2023",
    time: "12:18 PM",
  },
  {
    id: 9,
    src: "http://dummyimage.com/130x100.png/ff4444/ffffff",
    catname: "College",
    eventname: "Babblestorm",
    location: "Banglore",
    ticketprice: "1125",
    ticketsize: "93922",
    likes: "036",
    description:
      "aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non",
    organiser: "Veum LLC",
    date: "03/19/2024",
    time: "6:47 AM",
  },
  {
    id: 10,
    src: "http://dummyimage.com/249x100.png/ff4444/ffffff",
    catname: "Business",
    eventname: "Jaxbean",
    location: "Chandigarh",
    ticketprice: "6482",
    ticketsize: "5",
    likes: "237",
    description:
      "praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante",
    organiser: "Mitchell Inc",
    date: "01/29/2024",
    time: "9:29 PM",
  },
  {
    id: 11,
    src: "http://dummyimage.com/119x100.png/dddddd/000000",
    catname: "Music",
    eventname: "Kazu",
    location: "Amritsar",
    ticketprice: "6400",
    ticketsize: "5",
    likes: "345",
    description:
      "commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non",
    organiser: "Hoeger Inc",
    date: "07/08/2023",
    time: "6:32 AM",
  },
  {
    id: 12,
    src: "http://dummyimage.com/139x100.png/cc0000/ffffff",
    catname: "Music",
    eventname: "Kwideo",
    location: "Mumbai",
    ticketprice: "0116",
    ticketsize: "79289",
    likes: "812",
    description:
      "et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis",
    organiser: "Padberg, Reinger and Cruickshank",
    date: "10/25/2023",
    time: "4:49 AM",
  },
  {
    id: 13,
    src: "http://dummyimage.com/179x100.png/dddddd/000000",
    catname: "College",
    eventname: "Chatterbridge",
    location: "Mumbai",
    ticketprice: "6733",
    ticketsize: "6263",
    likes: "980",
    description:
      "consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo",
    organiser: "Dare Group",
    date: "09/29/2023",
    time: "7:28 AM",
  },
  {
    id: 14,
    src: "http://dummyimage.com/177x100.png/dddddd/000000",
    catname: "College",
    eventname: "Yakitri",
    location: "Amritsar",
    ticketprice: "6529",
    ticketsize: "12829",
    likes: "232",
    description:
      "venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam",
    organiser: "Moore, Muller and Crist",
    date: "04/24/2023",
    time: "10:56 PM",
  },
  {
    id: 15,
    src: "http://dummyimage.com/124x100.png/ff4444/ffffff",
    catname: "Business",
    eventname: "Leenti",
    location: "Chandigarh",
    ticketprice: "6510",
    ticketsize: "75375",
    likes: "319",
    description:
      "quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse",
    organiser: "Thiel, Ziemann and Feeney",
    date: "03/17/2024",
    time: "6:16 PM",
  },
  {
    id: 16,
    src: "http://dummyimage.com/236x100.png/5fa2dd/ffffff",
    catname: "College",
    eventname: "Ntags",
    location: "Banglore",
    ticketprice: "2945",
    ticketsize: "043",
    likes: "519",
    description:
      "montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id",
    organiser: "Denesik, Rau and Wisozk",
    date: "10/16/2023",
    time: "9:01 PM",
  },
  {
    id: 17,
    src: "http://dummyimage.com/170x100.png/cc0000/ffffff",
    catname: "Music",
    eventname: "Rhyloo",
    location: "Banglore",
    ticketprice: "5510",
    ticketsize: "614",
    likes: "216",
    description:
      "sed magna at nunc commodo placerat praesent blandit nam nulla integer pede",
    organiser: "Sporer-Buckridge",
    date: "01/13/2024",
    time: "11:38 AM",
  },
  {
    id: 18,
    src: "http://dummyimage.com/218x100.png/ff4444/ffffff",
    catname: "College",
    eventname: "Aivee",
    location: "Mumbai",
    ticketprice: "0364",
    ticketsize: "32",
    likes: "179",
    description:
      "nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac",
    organiser: "Feeney Group",
    date: "07/16/2023",
    time: "2:47 PM",
  },
  // {
  //   id: 19,
  //   src: "http://dummyimage.com/114x100.png/cc0000/ffffff",
  //   catname: "College",
  //   eventname: "Blogspan",
  //   location: "Delhi",
  //   ticketprice: "7181",
  //   ticketsize: "62",
  //   likes: "147",
  //   description:
  //     "et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet",
  //   organiser: "Cremin, Nicolas and Jaskolski",
  //   date: "12/15/2023",
  //   time: "3:58 AM",
  // },
  // {
  //   id: 20,
  //   src: "http://dummyimage.com/235x100.png/cc0000/ffffff",
  //   catname: "Music",
  //   eventname: "Browsecat",
  //   location: "Chandigarh",
  //   ticketprice: "2101",
  //   ticketsize: "65",
  //   likes: "375",
  //   description: "lectus in est risus auctor sed tristique in tempus sit amet",
  //   organiser: "Denesik, Haag and Kihn",
  //   date: "02/05/2024",
  //   time: "12:55 PM",
  // },
  // {
  //   id: 21,
  //   src: "http://dummyimage.com/125x100.png/dddddd/000000",
  //   catname: "Music",
  //   eventname: "Gabvine",
  //   location: "Banglore",
  //   ticketprice: "6701",
  //   ticketsize: "73749",
  //   likes: "484",
  //   description:
  //     "elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget",
  //   organiser: "Purdy, Cremin and Williamson",
  //   date: "08/22/2023",
  //   time: "6:47 PM",
  // },
  // {
  //   id: 22,
  //   src: "http://dummyimage.com/122x100.png/ff4444/ffffff",
  //   catname: "Business",
  //   eventname: "Edgeify",
  //   location: "Mumbai",
  //   ticketprice: "8200",
  //   ticketsize: "1097",
  //   likes: "729",
  //   description:
  //     "donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum",
  //   organiser: "Jakubowski-Wintheiser",
  //   date: "12/20/2023",
  //   time: "10:20 AM",
  // },
  // {
  //   id: 23,
  //   src: "http://dummyimage.com/202x100.png/ff4444/ffffff",
  //   catname: "Music",
  //   eventname: "Fliptune",
  //   location: "Mumbai",
  //   ticketprice: "6755",
  //   ticketsize: "66",
  //   likes: "444",
  //   description: "duis consequat dui nec nisi volutpat eleifend donec ut dolor",
  //   organiser: "King Group",
  //   date: "02/18/2024",
  //   time: "3:06 AM",
  // },
  // {
  //   id: 24,
  //   src: "http://dummyimage.com/116x100.png/dddddd/000000",
  //   catname: "Business",
  //   eventname: "Tazzy",
  //   location: "Chandigarh",
  //   ticketprice: "1012",
  //   ticketsize: "4657",
  //   likes: "674",
  //   description:
  //     "ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis",
  //   organiser: "Schroeder Group",
  //   date: "08/01/2023",
  //   time: "10:49 AM",
  // },
  // {
  //   id: 25,
  //   src: "http://dummyimage.com/167x100.png/ff4444/ffffff",
  //   catname: "College",
  //   eventname: "Mycat",
  //   location: "Amritsar",
  //   ticketprice: "4029",
  //   ticketsize: "46",
  //   likes: "909",
  //   description:
  //     "consequat lectus in est risus auctor sed tristique in tempus sit",
  //   organiser: "Swift-Kris",
  //   date: "02/02/2024",
  //   time: "7:03 PM",
  // },
  // {
  //   id: 26,
  //   src: "http://dummyimage.com/146x100.png/dddddd/000000",
  //   catname: "Music",
  //   eventname: "Mybuzz",
  //   location: "Delhi",
  //   ticketprice: "4113",
  //   ticketsize: "2",
  //   likes: "309",
  //   description:
  //     "condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar",
  //   organiser: "Franecki LLC",
  //   date: "11/20/2023",
  //   time: "4:55 PM",
  // },
  // {
  //   id: 27,
  //   src: "http://dummyimage.com/144x100.png/ff4444/ffffff",
  //   catname: "Business",
  //   eventname: "Innotype",
  //   location: "Delhi",
  //   ticketprice: "8310",
  //   ticketsize: "87",
  //   likes: "340",
  //   description:
  //     "amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus",
  //   organiser: "Mann-Kilback",
  //   date: "05/06/2023",
  //   time: "4:55 PM",
  // },
  // {
  //   id: 28,
  //   src: "http://dummyimage.com/150x100.png/5fa2dd/ffffff",
  //   catname: "Business",
  //   eventname: "Wordify",
  //   location: "Chandigarh",
  //   ticketprice: "9489",
  //   ticketsize: "504",
  //   likes: "024",
  //   description:
  //     "accumsan odio curabitur convallis duis consequat dui nec nisi volutpat",
  //   organiser: "Kris, Daniel and Schaden",
  //   date: "04/17/2023",
  //   time: "12:17 PM",
  // },
  // {
  //   id: 29,
  //   src: "http://dummyimage.com/242x100.png/5fa2dd/ffffff",
  //   catname: "College",
  //   eventname: "Youspan",
  //   location: "Amritsar",
  //   ticketprice: "7335",
  //   ticketsize: "43",
  //   likes: "160",
  //   description:
  //     "eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec",
  //   organiser: "Boehm Group",
  //   date: "06/18/2023",
  //   time: "6:10 AM",
  // },
  // {
  //   id: 30,
  //   src: "http://dummyimage.com/153x100.png/dddddd/000000",
  //   catname: "Music",
  //   eventname: "Mynte",
  //   location: "Chandigarh",
  //   ticketprice: "9838",
  //   ticketsize: "5764",
  //   likes: "487",
  //   description:
  //     "quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse",
  //   organiser: "Brakus Group",
  //   date: "10/31/2023",
  //   time: "6:48 AM",
  // },
  // {
  //   id: 31,
  //   src: "http://dummyimage.com/197x100.png/5fa2dd/ffffff",
  //   catname: "Business",
  //   eventname: "Quatz",
  //   location: "Banglore",
  //   ticketprice: "7148",
  //   ticketsize: "16",
  //   likes: "984",
  //   description:
  //     "venenatis non sodales sed tincidunt eu felis fusce posuere felis",
  //   organiser: "Abernathy and Sons",
  //   date: "08/30/2023",
  //   time: "5:36 AM",
  // },
  // {
  //   id: 32,
  //   src: "http://dummyimage.com/208x100.png/cc0000/ffffff",
  //   catname: "College",
  //   eventname: "Dynava",
  //   location: "Mumbai",
  //   ticketprice: "7467",
  //   ticketsize: "06565",
  //   likes: "461",
  //   description: "in est risus auctor sed tristique in tempus sit amet sem",
  //   organiser: "Wunsch LLC",
  //   date: "09/25/2023",
  //   time: "12:40 AM",
  // },
  // {
  //   id: 33,
  //   src: "http://dummyimage.com/195x100.png/ff4444/ffffff",
  //   catname: "Business",
  //   eventname: "Zoombox",
  //   location: "Delhi",
  //   ticketprice: "7751",
  //   ticketsize: "87311",
  //   likes: "291",
  //   description:
  //     "id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus",
  //   organiser: "Krajcik, Funk and Collins",
  //   date: "08/26/2023",
  //   time: "7:56 PM",
  // },
  // {
  //   id: 34,
  //   src: "http://dummyimage.com/108x100.png/ff4444/ffffff",
  //   catname: "Music",
  //   eventname: "Ntags",
  //   location: "Delhi",
  //   ticketprice: "4702",
  //   ticketsize: "04172",
  //   likes: "036",
  //   description:
  //     "diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales",
  //   organiser: "Okuneva, Considine and Ortiz",
  //   date: "06/29/2023",
  //   time: "4:05 AM",
  // },
  // {
  //   id: 35,
  //   src: "http://dummyimage.com/168x100.png/ff4444/ffffff",
  //   catname: "College",
  //   eventname: "Oyoba",
  //   location: "Mumbai",
  //   ticketprice: "0146",
  //   ticketsize: "1330",
  //   likes: "594",
  //   description:
  //     "aliquet maecenas leo odio condimentum id luctus nec molestie sed justo",
  //   organiser: "Feeney, Mosciski and Lebsack",
  //   date: "08/06/2023",
  //   time: "6:11 AM",
  // },
  // {
  //   id: 36,
  //   src: "http://dummyimage.com/194x100.png/dddddd/000000",
  //   catname: "Business",
  //   eventname: "Jamia",
  //   location: "Amritsar",
  //   ticketprice: "4128",
  //   ticketsize: "78",
  //   likes: "891",
  //   description:
  //     "varius nulla facilisi cras non velit nec nisi vulputate nonummy",
  //   organiser: "Keeling Group",
  //   date: "07/16/2023",
  //   time: "11:39 PM",
  // },
  // {
  //   id: 37,
  //   src: "http://dummyimage.com/155x100.png/dddddd/000000",
  //   catname: "College",
  //   eventname: "Rhycero",
  //   location: "Banglore",
  //   ticketprice: "7869",
  //   ticketsize: "53686",
  //   likes: "302",
  //   description:
  //     "in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit",
  //   organiser: "Becker-Huels",
  //   date: "04/09/2023",
  //   time: "8:35 AM",
  // },
  // {
  //   id: 38,
  //   src: "http://dummyimage.com/161x100.png/dddddd/000000",
  //   catname: "Music",
  //   eventname: "Eidel",
  //   location: "Mumbai",
  //   ticketprice: "1796",
  //   ticketsize: "7",
  //   likes: "076",
  //   description:
  //     "odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum",
  //   organiser: "Murphy-Rodriguez",
  //   date: "08/21/2023",
  //   time: "12:32 AM",
  // },
  // {
  //   id: 39,
  //   src: "http://dummyimage.com/181x100.png/dddddd/000000",
  //   catname: "Music",
  //   eventname: "Centidel",
  //   location: "Banglore",
  //   ticketprice: "6659",
  //   ticketsize: "9",
  //   likes: "609",
  //   description:
  //     "faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in",
  //   organiser: "Wisoky-Towne",
  //   date: "02/14/2024",
  //   time: "7:31 PM",
  // },
  // {
  //   id: 40,
  //   src: "http://dummyimage.com/111x100.png/ff4444/ffffff",
  //   catname: "Music",
  //   eventname: "Talane",
  //   location: "Chandigarh",
  //   ticketprice: "9828",
  //   ticketsize: "091",
  //   likes: "395",
  //   description:
  //     "integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui",
  //   organiser: "Hand Group",
  //   date: "06/15/2023",
  //   time: "3:42 PM",
  // },
  // {
  //   id: 41,
  //   src: "http://dummyimage.com/174x100.png/ff4444/ffffff",
  //   catname: "College",
  //   eventname: "College",
  //   location: "Amritsar",
  //   ticketprice: "2786",
  //   ticketsize: "06",
  //   likes: "572",
  //   description:
  //     "in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus",
  //   organiser: "Effertz, Larson and Haag",
  //   date: "12/25/2023",
  //   time: "3:04 AM",
  // },
  // {
  //   id: 42,
  //   src: "http://dummyimage.com/227x100.png/5fa2dd/ffffff",
  //   catname: "Business",
  //   eventname: "Podcat",
  //   location: "Chandigarh",
  //   ticketprice: "6941",
  //   ticketsize: "37",
  //   likes: "800",
  //   description:
  //     "volutpat sapien arcu sed augue aliquam erat volutpat in congue",
  //   organiser: "Reichert, Larkin and Fahey",
  //   date: "11/20/2023",
  //   time: "12:04 AM",
  // },
  // {
  //   id: 43,
  //   src: "http://dummyimage.com/132x100.png/5fa2dd/ffffff",
  //   catname: "College",
  //   eventname: "Muxo",
  //   location: "Banglore",
  //   ticketprice: "3794",
  //   ticketsize: "1",
  //   likes: "133",
  //   description:
  //     "nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam",
  //   organiser: "Smitham, Rempel and Rosenbaum",
  //   date: "08/08/2023",
  //   time: "6:25 PM",
  // },
  // {
  //   id: 44,
  //   src: "http://dummyimage.com/216x100.png/cc0000/ffffff",
  //   catname: "Music",
  //   eventname: "Buzzshare",
  //   location: "Mumbai",
  //   ticketprice: "3408",
  //   ticketsize: "40343",
  //   likes: "331",
  //   description:
  //     "dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras",
  //   organiser: "Hilll-Heaney",
  //   date: "08/26/2023",
  //   time: "3:05 PM",
  // },
  // {
  //   id: 45,
  //   src: "http://dummyimage.com/124x100.png/dddddd/000000",
  //   catname: "College",
  //   eventname: "Zoomzone",
  //   location: "Chandigarh",
  //   ticketprice: "3701",
  //   ticketsize: "13",
  //   likes: "450",
  //   description:
  //     "eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum",
  //   organiser: "Jaskolski Inc",
  //   date: "07/10/2023",
  //   time: "6:55 AM",
  // },
  // {
  //   id: 46,
  //   src: "http://dummyimage.com/235x100.png/cc0000/ffffff",
  //   catname: "Business",
  //   eventname: "Katz",
  //   location: "Banglore",
  //   ticketprice: "0627",
  //   ticketsize: "52",
  //   likes: "957",
  //   description:
  //     "in porttitor pede justo eu massa donec dapibus duis at velit eu est",
  //   organiser: "Bashirian-Wunsch",
  //   date: "03/31/2024",
  //   time: "10:10 PM",
  // },
  // {
  //   id: 47,
  //   src: "http://dummyimage.com/156x100.png/dddddd/000000",
  //   catname: "Music",
  //   eventname: "Roomm",
  //   location: "Delhi",
  //   ticketprice: "4555",
  //   ticketsize: "7623",
  //   likes: "767",
  //   description:
  //     "in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu",
  //   organiser: "Brakus-Cole",
  //   date: "09/08/2023",
  //   time: "10:52 PM",
  // },
  // {
  //   id: 48,
  //   src: "http://dummyimage.com/215x100.png/5fa2dd/ffffff",
  //   catname: "Music",
  //   eventname: "Skynoodle",
  //   location: "Amritsar",
  //   ticketprice: "2492",
  //   ticketsize: "44",
  //   likes: "955",
  //   description:
  //     "neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in",
  //   organiser: "Keeling LLC",
  //   date: "12/06/2023",
  //   time: "5:37 PM",
  // },
  // {
  //   id: 49,
  //   src: "http://dummyimage.com/163x100.png/ff4444/ffffff",
  //   catname: "Business",
  //   eventname: "Tagopia",
  //   location: "Mumbai",
  //   ticketprice: "2613",
  //   ticketsize: "60",
  //   likes: "340",
  //   description:
  //     "rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum",
  //   organiser: "Franecki-Beer",
  //   date: "05/19/2023",
  //   time: "12:51 PM",
  // },
  // {
  //   id: 50,
  //   src: "http://dummyimage.com/161x100.png/cc0000/ffffff",
  //   catname: "College",
  //   eventname: "Kamba",
  //   location: "Delhi",
  //   ticketprice: "8992",
  //   ticketsize: "1804",
  //   likes: "761",
  //   description:
  //     "odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem",
  //   organiser: "Spencer and Sons",
  //   date: "06/17/2023",
  //   time: "8:47 AM",
  // },
  // {
  //   id: 51,
  //   src: "http://dummyimage.com/237x100.png/cc0000/ffffff",
  //   catname: "Business",
  //   eventname: "Aivee",
  //   location: "Chandigarh",
  //   ticketprice: "9272",
  //   ticketsize: "3023",
  //   likes: "044",
  //   description:
  //     "id luctus nec molestie sed justo pellentesque viverra pede ac diam",
  //   organiser: "Strosin, Muller and Donnelly",
  //   date: "12/05/2023",
  //   time: "6:24 PM",
  // },
  // {
  //   id: 52,
  //   src: "http://dummyimage.com/149x100.png/5fa2dd/ffffff",
  //   catname: "Music",
  //   eventname: "Ozu",
  //   location: "Amritsar",
  //   ticketprice: "6260",
  //   ticketsize: "456",
  //   likes: "823",
  //   description:
  //     "posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum",
  //   organiser: "Hayes Group",
  //   date: "12/25/2023",
  //   time: "1:33 PM",
  // },
  // {
  //   id: 53,
  //   src: "http://dummyimage.com/152x100.png/dddddd/000000",
  //   catname: "College",
  //   eventname: "Eayo",
  //   location: "Amritsar",
  //   ticketprice: "7327",
  //   ticketsize: "72",
  //   likes: "317",
  //   description:
  //     "sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis",
  //   organiser: "O'Kon and Sons",
  //   date: "02/05/2024",
  //   time: "5:11 PM",
  // },
  // {
  //   id: 54,
  //   src: "http://dummyimage.com/184x100.png/ff4444/ffffff",
  //   catname: "Music",
  //   eventname: "Jaxworks",
  //   location: "Chandigarh",
  //   ticketprice: "8031",
  //   ticketsize: "242",
  //   likes: "742",
  //   description:
  //     "vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet",
  //   organiser: "Hills and Sons",
  //   date: "10/02/2023",
  //   time: "9:41 PM",
  // },
  // {
  //   id: 55,
  //   src: "http://dummyimage.com/109x100.png/ff4444/ffffff",
  //   catname: "College",
  //   eventname: "Aimbo",
  //   location: "Mumbai",
  //   ticketprice: "6102",
  //   ticketsize: "21817",
  //   likes: "451",
  //   description:
  //     "sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo",
  //   organiser: "Wintheiser, Bartoletti and Brekke",
  //   date: "12/21/2023",
  //   time: "2:37 PM",
  // },
  // {
  //   id: 56,
  //   src: "http://dummyimage.com/249x100.png/ff4444/ffffff",
  //   catname: "Music",
  //   eventname: "Babbleopia",
  //   location: "Banglore",
  //   ticketprice: "6620",
  //   ticketsize: "05717",
  //   likes: "713",
  //   description:
  //     "non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus",
  //   organiser: "Walsh-Bashirian",
  //   date: "05/27/2023",
  //   time: "2:51 AM",
  // },
  // {
  //   id: 57,
  //   src: "http://dummyimage.com/242x100.png/dddddd/000000",
  //   catname: "Business",
  //   eventname: "Myworks",
  //   location: "Chandigarh",
  //   ticketprice: "2424",
  //   ticketsize: "3",
  //   likes: "677",
  //   description:
  //     "hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat",
  //   organiser: "Erdman, Kunde and Hauck",
  //   date: "11/22/2023",
  //   time: "12:58 AM",
  // },
  // {
  //   id: 58,
  //   src: "http://dummyimage.com/207x100.png/ff4444/ffffff",
  //   catname: "College",
  //   eventname: "Jaxworks",
  //   location: "Amritsar",
  //   ticketprice: "8945",
  //   ticketsize: "97",
  //   likes: "373",
  //   description:
  //     "maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas",
  //   organiser: "Reichel-Renner",
  //   date: "08/07/2023",
  //   time: "2:16 PM",
  // },
  // {
  //   id: 59,
  //   src: "http://dummyimage.com/140x100.png/5fa2dd/ffffff",
  //   catname: "Music",
  //   eventname: "Vimbo",
  //   location: "Banglore",
  //   ticketprice: "2548",
  //   ticketsize: "73",
  //   likes: "510",
  //   description:
  //     "cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit",
  //   organiser: "Jerde, MacGyver and Murazik",
  //   date: "12/08/2023",
  //   time: "3:30 AM",
  // },
  // {
  //   id: 60,
  //   src: "http://dummyimage.com/195x100.png/cc0000/ffffff",
  //   catname: "Music",
  //   eventname: "Livetube",
  //   location: "Amritsar",
  //   ticketprice: "0894",
  //   ticketsize: "61273",
  //   likes: "797",
  //   description:
  //     "vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna",
  //   organiser: "Grant and Sons",
  //   date: "07/25/2023",
  //   time: "3:32 AM",
  // },
  // {
  //   id: 61,
  //   src: "http://dummyimage.com/215x100.png/dddddd/000000",
  //   catname: "College",
  //   eventname: "Oodoo",
  //   location: "Mumbai",
  //   ticketprice: "5456",
  //   ticketsize: "828",
  //   likes: "360",
  //   description:
  //     "eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis",
  //   organiser: "Thompson-Schamberger",
  //   date: "06/03/2023",
  //   time: "12:28 PM",
  // },
  // {
  //   id: 62,
  //   src: "http://dummyimage.com/207x100.png/ff4444/ffffff",
  //   catname: "College",
  //   eventname: "Tagfeed",
  //   location: "Delhi",
  //   ticketprice: "6648",
  //   ticketsize: "86",
  //   likes: "485",
  //   description:
  //     "vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum",
  //   organiser: "Nolan Group",
  //   date: "09/25/2023",
  //   time: "8:28 PM",
  // },
  // {
  //   id: 63,
  //   src: "http://dummyimage.com/185x100.png/ff4444/ffffff",
  //   catname: "Business",
  //   eventname: "Skippad",
  //   location: "Chandigarh",
  //   ticketprice: "6999",
  //   ticketsize: "788",
  //   likes: "849",
  //   description:
  //     "sed accumsan felis ut at dolor quis odio consequat varius integer ac leo",
  //   organiser: "West-Weissnat",
  //   date: "01/22/2024",
  //   time: "7:29 PM",
  // },
  // {
  //   id: 64,
  //   src: "http://dummyimage.com/188x100.png/cc0000/ffffff",
  //   catname: "College",
  //   eventname: "Topicstorm",
  //   location: "Amritsar",
  //   ticketprice: "8998",
  //   ticketsize: "6",
  //   likes: "999",
  //   description:
  //     "placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget",
  //   organiser: "Borer Group",
  //   date: "01/10/2024",
  //   time: "7:56 PM",
  // },
  // {
  //   id: 65,
  //   src: "http://dummyimage.com/129x100.png/cc0000/ffffff",
  //   catname: "Music",
  //   eventname: "Kanoodle",
  //   location: "Delhi",
  //   ticketprice: "4614",
  //   ticketsize: "7064",
  //   likes: "499",
  //   description:
  //     "vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere",
  //   organiser: "Heidenreich Inc",
  //   date: "12/28/2023",
  //   time: "2:09 AM",
  // },
  // {
  //   id: 66,
  //   src: "http://dummyimage.com/188x100.png/ff4444/ffffff",
  //   catname: "College",
  //   eventname: "Zoombeat",
  //   location: "Banglore",
  //   ticketprice: "8652",
  //   ticketsize: "24689",
  //   likes: "823",
  //   description:
  //     "ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia",
  //   organiser: "Wehner, Watsica and Parker",
  //   date: "01/08/2024",
  //   time: "4:42 AM",
  // },
  // {
  //   id: 67,
  //   src: "http://dummyimage.com/241x100.png/dddddd/000000",
  //   catname: "Music",
  //   eventname: "Ntag",
  //   location: "Chandigarh",
  //   ticketprice: "9825",
  //   ticketsize: "159",
  //   likes: "069",
  //   description:
  //     "tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam",
  //   organiser: "Hintz, Hahn and Hirthe",
  //   date: "06/21/2023",
  //   time: "3:45 AM",
  // },
  // {
  //   id: 68,
  //   src: "http://dummyimage.com/225x100.png/cc0000/ffffff",
  //   catname: "College",
  //   eventname: "Mita",
  //   location: "Delhi",
  //   ticketprice: "5841",
  //   ticketsize: "06",
  //   likes: "460",
  //   description:
  //     "orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin",
  //   organiser: "Haley and Sons",
  //   date: "04/07/2024",
  //   time: "11:41 AM",
  // },
  // {
  //   id: 69,
  //   src: "http://dummyimage.com/112x100.png/5fa2dd/ffffff",
  //   catname: "Business",
  //   eventname: "Ailane",
  //   location: "Chandigarh",
  //   ticketprice: "2681",
  //   ticketsize: "868",
  //   likes: "009",
  //   description:
  //     "dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor",
  //   organiser: "Mohr LLC",
  //   date: "02/08/2024",
  //   time: "3:33 AM",
  // },
  // {
  //   id: 70,
  //   src: "http://dummyimage.com/234x100.png/dddddd/000000",
  //   catname: "College",
  //   eventname: "Kwimbee",
  //   location: "Amritsar",
  //   ticketprice: "2081",
  //   ticketsize: "34437",
  //   likes: "801",
  //   description:
  //     "donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum",
  //   organiser: "Brekke-Wuckert",
  //   date: "04/11/2023",
  //   time: "3:46 PM",
  // },
  // {
  //   id: 71,
  //   src: "http://dummyimage.com/146x100.png/dddddd/000000",
  //   catname: "College",
  //   eventname: "SkipIt",
  //   location: "Mumbai",
  //   ticketprice: "7250",
  //   ticketsize: "316",
  //   likes: "641",
  //   description:
  //     "dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus",
  //   organiser: "Thompson, Lockman and Koepp",
  //   date: "01/27/2024",
  //   time: "6:29 PM",
  // },
  // {
  //   id: 72,
  //   src: "http://dummyimage.com/222x100.png/dddddd/000000",
  //   catname: "Music",
  //   eventname: "Abatz",
  //   location: "Delhi",
  //   ticketprice: "9453",
  //   ticketsize: "7",
  //   likes: "172",
  //   description:
  //     "nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec",
  //   organiser: "Daniel-Krajcik",
  //   date: "05/21/2023",
  //   time: "3:45 PM",
  // },
  // {
  //   id: 73,
  //   src: "http://dummyimage.com/201x100.png/cc0000/ffffff",
  //   catname: "Business",
  //   eventname: "Eidel",
  //   location: "Delhi",
  //   ticketprice: "9524",
  //   ticketsize: "64",
  //   likes: "630",
  //   description: "dui vel nisl duis ac nibh fusce lacus purus aliquet",
  //   organiser: "Beier LLC",
  //   date: "10/02/2023",
  //   time: "12:36 PM",
  // },
  // {
  //   id: 74,
  //   src: "http://dummyimage.com/216x100.png/dddddd/000000",
  //   catname: "Music",
  //   eventname: "Twitterbridge",
  //   location: "Banglore",
  //   ticketprice: "5496",
  //   ticketsize: "90841",
  //   likes: "625",
  //   description:
  //     "vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere",
  //   organiser: "Jaskolski LLC",
  //   date: "01/07/2024",
  //   time: "3:33 AM",
  // },
  // {
  //   id: 75,
  //   src: "http://dummyimage.com/194x100.png/cc0000/ffffff",
  //   catname: "College",
  //   eventname: "Podcat",
  //   location: "Chandigarh",
  //   ticketprice: "4178",
  //   ticketsize: "40",
  //   likes: "199",
  //   description:
  //     "duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis",
  //   organiser: "Hackett-Raynor",
  //   date: "01/10/2024",
  //   time: "1:03 PM",
  // },
  // {
  //   id: 76,
  //   src: "http://dummyimage.com/109x100.png/ff4444/ffffff",
  //   catname: "Business",
  //   eventname: "Youtags",
  //   location: "Mumbai",
  //   ticketprice: "7241",
  //   ticketsize: "880",
  //   likes: "409",
  //   description:
  //     "eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in",
  //   organiser: "Heaney, Pfeffer and Weissnat",
  //   date: "04/22/2023",
  //   time: "3:45 PM",
  // },
  // {
  //   id: 77,
  //   src: "http://dummyimage.com/112x100.png/dddddd/000000",
  //   catname: "College",
  //   eventname: "Devpulse",
  //   location: "Amritsar",
  //   ticketprice: "2607",
  //   ticketsize: "45776",
  //   likes: "696",
  //   description:
  //     "lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis",
  //   organiser: "Cremin-Spencer",
  //   date: "12/20/2023",
  //   time: "3:06 AM",
  // },
  // {
  //   id: 78,
  //   src: "http://dummyimage.com/144x100.png/5fa2dd/ffffff",
  //   catname: "College",
  //   eventname: "Brainsphere",
  //   location: "Mumbai",
  //   ticketprice: "1370",
  //   ticketsize: "4389",
  //   likes: "180",
  //   description:
  //     "eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus",
  //   organiser: "O'Hara, Weimann and Bauch",
  //   date: "02/29/2024",
  //   time: "11:01 PM",
  // },
  // {
  //   id: 79,
  //   src: "http://dummyimage.com/119x100.png/cc0000/ffffff",
  //   catname: "Music",
  //   eventname: "Yakijo",
  //   location: "Banglore",
  //   ticketprice: "5244",
  //   ticketsize: "892",
  //   likes: "183",
  //   description:
  //     "vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue",
  //   organiser: "Wilkinson, Wolf and Botsford",
  //   date: "10/12/2023",
  //   time: "12:10 PM",
  // },
  // {
  //   id: 80,
  //   src: "http://dummyimage.com/171x100.png/cc0000/ffffff",
  //   catname: "College",
  //   eventname: "Riffpath",
  //   location: "Amritsar",
  //   ticketprice: "9421",
  //   ticketsize: "469",
  //   likes: "296",
  //   description:
  //     "mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero",
  //   organiser: "Walsh, Bauch and Keebler",
  //   date: "12/23/2023",
  //   time: "4:09 AM",
  // },
  // {
  //   id: 81,
  //   src: "http://dummyimage.com/117x100.png/ff4444/ffffff",
  //   catname: "Music",
  //   eventname: "Eire",
  //   location: "Banglore",
  //   ticketprice: "7570",
  //   ticketsize: "43",
  //   likes: "741",
  //   description:
  //     "proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue",
  //   organiser: "Stehr-Fadel",
  //   date: "07/18/2023",
  //   time: "9:45 PM",
  // },
  // {
  //   id: 82,
  //   src: "http://dummyimage.com/115x100.png/ff4444/ffffff",
  //   catname: "College",
  //   eventname: "Trudoo",
  //   location: "Delhi",
  //   ticketprice: "0547",
  //   ticketsize: "9979",
  //   likes: "389",
  //   description:
  //     "mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit",
  //   organiser: "Schinner Group",
  //   date: "12/02/2023",
  //   time: "9:36 AM",
  // },
  // {
  //   id: 83,
  //   src: "http://dummyimage.com/225x100.png/ff4444/ffffff",
  //   catname: "Business",
  //   eventname: "Jetwire",
  //   location: "Delhi",
  //   ticketprice: "7893",
  //   ticketsize: "69",
  //   likes: "192",
  //   description:
  //     "posuere cubilia curae nulla dapibus dolor vel est donec odio justo",
  //   organiser: "Walker, Morissette and Hickle",
  //   date: "01/05/2024",
  //   time: "7:01 PM",
  // },
  // {
  //   id: 84,
  //   src: "http://dummyimage.com/247x100.png/5fa2dd/ffffff",
  //   catname: "Music",
  //   eventname: "Realblab",
  //   location: "Delhi",
  //   ticketprice: "2072",
  //   ticketsize: "49",
  //   likes: "652",
  //   description:
  //     "convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum",
  //   organiser: "Bauch LLC",
  //   date: "04/30/2023",
  //   time: "11:30 PM",
  // },
  // {
  //   id: 85,
  //   src: "http://dummyimage.com/207x100.png/ff4444/ffffff",
  //   catname: "Business",
  //   eventname: "Oloo",
  //   location: "Amritsar",
  //   ticketprice: "8407",
  //   ticketsize: "03",
  //   likes: "946",
  //   description:
  //     "at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci",
  //   organiser: "Lynch-Purdy",
  //   date: "11/03/2023",
  //   time: "6:42 AM",
  // },
  // {
  //   id: 86,
  //   src: "http://dummyimage.com/239x100.png/5fa2dd/ffffff",
  //   catname: "College",
  //   eventname: "Jayo",
  //   location: "Chandigarh",
  //   ticketprice: "5277",
  //   ticketsize: "12102",
  //   likes: "126",
  //   description:
  //     "elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas",
  //   organiser: "Kohler Group",
  //   date: "01/05/2024",
  //   time: "11:53 AM",
  // },
  // {
  //   id: 87,
  //   src: "http://dummyimage.com/196x100.png/ff4444/ffffff",
  //   catname: "Music",
  //   eventname: "Youtags",
  //   location: "Mumbai",
  //   ticketprice: "5789",
  //   ticketsize: "7",
  //   likes: "889",
  //   description:
  //     "amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis",
  //   organiser: "Gottlieb, Lebsack and Lebsack",
  //   date: "01/17/2024",
  //   time: "11:05 AM",
  // },
  // {
  //   id: 88,
  //   src: "http://dummyimage.com/218x100.png/5fa2dd/ffffff",
  //   catname: "College",
  //   eventname: "Jabberstorm",
  //   location: "Delhi",
  //   ticketprice: "2013",
  //   ticketsize: "7208",
  //   likes: "507",
  //   description:
  //     "vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel",
  //   organiser: "O'Hara Inc",
  //   date: "09/09/2023",
  //   time: "4:52 PM",
  // },
  // {
  //   id: 89,
  //   src: "http://dummyimage.com/179x100.png/cc0000/ffffff",
  //   catname: "Business",
  //   eventname: "Zoozzy",
  //   location: "Amritsar",
  //   ticketprice: "1725",
  //   ticketsize: "289",
  //   likes: "525",
  //   description:
  //     "dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus",
  //   organiser: "Bartell LLC",
  //   date: "04/04/2024",
  //   time: "7:31 AM",
  // },
  // {
  //   id: 90,
  //   src: "http://dummyimage.com/167x100.png/dddddd/000000",
  //   catname: "Music",
  //   eventname: "Skimia",
  //   location: "Chandigarh",
  //   ticketprice: "5034",
  //   ticketsize: "07",
  //   likes: "579",
  //   description:
  //     "morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id",
  //   organiser: "Haley-Mann",
  //   date: "10/17/2023",
  //   time: "1:46 PM",
  // },
  // {
  //   id: 91,
  //   src: "http://dummyimage.com/120x100.png/cc0000/ffffff",
  //   catname: "Music",
  //   eventname: "Zooveo",
  //   location: "Delhi",
  //   ticketprice: "4632",
  //   ticketsize: "234",
  //   likes: "900",
  //   description:
  //     "dolor sit amet consectetuer adipiscing elit proin risus praesent lectus vestibulum quam sapien varius ut blandit",
  //   organiser: "Jakubowski, Keeling and Fisher",
  //   date: "06/24/2023",
  //   time: "9:33 AM",
  // },
  // {
  //   id: 92,
  //   src: "http://dummyimage.com/246x100.png/ff4444/ffffff",
  //   catname: "Business",
  //   eventname: "Browsedrive",
  //   location: "Banglore",
  //   ticketprice: "1635",
  //   ticketsize: "51060",
  //   likes: "017",
  //   description:
  //     "sed magna at nunc commodo placerat praesent blandit nam nulla",
  //   organiser: "Krajcik-Altenwerth",
  //   date: "04/06/2024",
  //   time: "12:30 PM",
  // },
  // {
  //   id: 93,
  //   src: "http://dummyimage.com/103x100.png/cc0000/ffffff",
  //   catname: "College",
  //   eventname: "Youbridge",
  //   location: "Banglore",
  //   ticketprice: "0255",
  //   ticketsize: "3478",
  //   likes: "108",
  //   description: "etiam faucibus cursus urna ut tellus nulla ut erat id",
  //   organiser: "Koepp, Donnelly and Anderson",
  //   date: "01/07/2024",
  //   time: "4:08 PM",
  // },
  // {
  //   id: 94,
  //   src: "http://dummyimage.com/232x100.png/cc0000/ffffff",
  //   catname: "Business",
  //   eventname: "Jazzy",
  //   location: "Mumbai",
  //   ticketprice: "8087",
  //   ticketsize: "8",
  //   likes: "725",
  //   description:
  //     "vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec",
  //   organiser: "Wehner, Dickinson and Turner",
  //   date: "06/21/2023",
  //   time: "7:20 AM",
  // },
  // {
  //   id: 95,
  //   src: "http://dummyimage.com/195x100.png/5fa2dd/ffffff",
  //   catname: "Music",
  //   eventname: "Buzzster",
  //   location: "Delhi",
  //   ticketprice: "4638",
  //   ticketsize: "2",
  //   likes: "670",
  //   description:
  //     "pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet",
  //   organiser: "Wehner-Jacobi",
  //   date: "06/19/2023",
  //   time: "11:20 PM",
  // },
  // {
  //   id: 96,
  //   src: "http://dummyimage.com/207x100.png/5fa2dd/ffffff",
  //   catname: "Business",
  //   eventname: "Muxo",
  //   location: "Amritsar",
  //   ticketprice: "8624",
  //   ticketsize: "445",
  //   likes: "270",
  //   description:
  //     "cursus id turpis integer aliquet massa id lobortis convallis tortor risus",
  //   organiser: "Stoltenberg LLC",
  //   date: "04/24/2023",
  //   time: "12:46 AM",
  // },
  // {
  //   id: 97,
  //   src: "http://dummyimage.com/119x100.png/ff4444/ffffff",
  //   catname: "College",
  //   eventname: "Yamia",
  //   location: "Amritsar",
  //   ticketprice: "1889",
  //   ticketsize: "2262",
  //   likes: "841",
  //   description:
  //     "quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus",
  //   organiser: "Huel-Price",
  //   date: "01/20/2024",
  //   time: "7:10 AM",
  // },
  // {
  //   id: 98,
  //   src: "http://dummyimage.com/150x100.png/dddddd/000000",
  //   catname: "College",
  //   eventname: "Shufflebeat",
  //   location: "Chandigarh",
  //   ticketprice: "5215",
  //   ticketsize: "2",
  //   likes: "867",
  //   description:
  //     "nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat",
  //   organiser: "Aufderhar Group",
  //   date: "03/11/2024",
  //   time: "9:16 AM",
  // },
  // {
  //   id: 99,
  //   src: "http://dummyimage.com/188x100.png/dddddd/000000",
  //   catname: "Business",
  //   eventname: "Wordware",
  //   location: "Mumbai",
  //   ticketprice: "0906",
  //   ticketsize: "88323",
  //   likes: "197",
  //   description:
  //     "praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus",
  //   organiser: "Beahan LLC",
  //   date: "11/07/2023",
  //   time: "9:15 AM",
  // },
  // {
  //   id: 100,
  //   src: "http://dummyimage.com/210x100.png/ff4444/ffffff",
  //   catname: "Music",
  //   eventname: "Leenti",
  //   location: "Banglore",
  //   ticketprice: "0373",
  //   ticketsize: "5815",
  //   likes: "870",
  //   description:
  //     "sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper",
  //   organiser: "Hodkiewicz, Bogan and Bernier",
  //   date: "11/01/2023",
  //   time: "7:39 PM",
  // },
  // {
  //   id: 101,
  //   src: "http://dummyimage.com/177x100.png/dddddd/000000",
  //   catname: "College",
  //   eventname: "Brainsphere",
  //   location: "Delhi",
  //   ticketprice: "4553",
  //   ticketsize: "0",
  //   likes: "788",
  //   description:
  //     "venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est",
  //   organiser: "Block, Stokes and Hermiston",
  //   date: "03/20/2024",
  //   time: "9:56 PM",
  // },
  // {
  //   id: 102,
  //   src: "http://dummyimage.com/132x100.png/dddddd/000000",
  //   catname: "Business",
  //   eventname: "Dablist",
  //   location: "Banglore",
  //   ticketprice: "4391",
  //   ticketsize: "07",
  //   likes: "219",
  //   description:
  //     "at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna",
  //   organiser: "Stamm and Sons",
  //   date: "05/16/2023",
  //   time: "6:06 PM",
  // },
  // {
  //   id: 103,
  //   src: "http://dummyimage.com/122x100.png/cc0000/ffffff",
  //   catname: "College",
  //   eventname: "Topiczoom",
  //   location: "Chandigarh",
  //   ticketprice: "1563",
  //   ticketsize: "4979",
  //   likes: "896",
  //   description:
  //     "est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac",
  //   organiser: "Graham-Bartoletti",
  //   date: "06/10/2023",
  //   time: "6:26 AM",
  // },
  // {
  //   id: 104,
  //   src: "http://dummyimage.com/156x100.png/ff4444/ffffff",
  //   catname: "Music",
  //   eventname: "Aimbo",
  //   location: "Delhi",
  //   ticketprice: "7500",
  //   ticketsize: "9",
  //   likes: "222",
  //   description:
  //     "at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat",
  //   organiser: "Ullrich, Little and Reichert",
  //   date: "08/17/2023",
  //   time: "10:35 AM",
  // },
  // {
  //   id: 105,
  //   src: "http://dummyimage.com/182x100.png/ff4444/ffffff",
  //   catname: "Music",
  //   eventname: "Vipe",
  //   location: "Banglore",
  //   ticketprice: "1221",
  //   ticketsize: "18",
  //   likes: "298",
  //   description:
  //     "quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin",
  //   organiser: "Senger, Hermann and O'Conner",
  //   date: "02/21/2024",
  //   time: "4:59 AM",
  // },
  // {
  //   id: 106,
  //   src: "http://dummyimage.com/235x100.png/ff4444/ffffff",
  //   catname: "Business",
  //   eventname: "Linktype",
  //   location: "Mumbai",
  //   ticketprice: "0475",
  //   ticketsize: "2469",
  //   likes: "477",
  //   description: "semper sapien a libero nam dui proin leo odio porttitor",
  //   organiser: "Durgan, Runte and Bednar",
  //   date: "07/17/2023",
  //   time: "5:13 PM",
  // },
  // {
  //   id: 107,
  //   src: "http://dummyimage.com/137x100.png/ff4444/ffffff",
  //   catname: "Music",
  //   eventname: "Demizz",
  //   location: "Chandigarh",
  //   ticketprice: "1583",
  //   ticketsize: "8",
  //   likes: "886",
  //   description:
  //     "consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in",
  //   organiser: "Klocko Group",
  //   date: "03/31/2024",
  //   time: "9:14 AM",
  // },
];
