const Events = [
  {
    id: 0,
    src: "/images/img0.jpg",
    catname: "Music",
    eventname: "Musical Night",
    location: "Ludhana",
    ticketprice: 500,
    ticketsize: 100, // for total no. of people
    likes: 0,
    description: "Dj Night with Radio Mirch Rj's",
    organiser: "Shivam",
    date: "SUN,APR 7",
    time: "8:00 PM",
  },
  {
    id: 1,
    src: "/images/img1.jpg",
    catname: "College",
    eventname: "International Conference on AI",
    location: "Chandigarh",
    ticketprice: 200,
    ticketsize: 250, // for total no. of people
    likes: 0,
    description: "Discussion on the future of AI",
    organiser: "CGC",
    date: "MON,APR 8",
    time: "10:00 AM",
  },
  {
    id: 2,
    src: "/images/img2.jpg",
    catname: "Music",
    eventname: "Musi Beats",
    location: "Chandigarh",
    ticketprice: 200,
    ticketsize: 1000, // for total no. of people
    likes: 0,
    description: "A Star Stud night with Super Star Singers",
    organiser: "Chandigarh University",
    date: "SAT,APR 13",
    time: "7:00 PM",
  },
  {
    id: 3,
    src: "/images/img3.jpg",
    catname: "Business",
    eventname: "Meet and Greet",
    location: "Chandigarh",
    ticketprice: 200,
    ticketsize: 50, // for total no. of people
    likes: 0,
    description: "Meet the business tycons in IT Industry",
    organiser: "Grazitti Interactive",
    date: "FRI,APR 12",
    time: "2:00 PM",
  },
  {
    id: 4,
    src: "/images/img4.jpg",
    catname: "Music",
    eventname: "Musical Concert",
    location: "Amritsar",
    ticketprice: 500,
    ticketsize: 5000, // for total no. of people
    likes: 0,
    description: "A Grand Music Concert by Diljit Doshanj",
    organiser: "GNDU",
    date: "SUN,APR 7",
    time: "9:00 PM",
  },
  {
    id: 5,
    src: "/images/img5.jpg",
    catname: "Business",
    eventname: "Meeting with Foreign Clients",
    location: "Delhi",
    ticketprice: 800,
    ticketsize: 450, // for total no. of people
    likes: 0,
    description: "Meeting our clients and getting to know them better",
    organiser: "IT Tech",
    date: "FRI,APR 19",
    time: "5:00 PM",
  },
  {
    id: 6,
    src: "/images/img6.jpg",
    catname: "College",
    eventname: "Cultural Fest",
    location: "Amritsar",
    ticketprice: 50,
    ticketsize: 1000, // for total no. of people
    likes: 0,
    description: "A fest to get closer to our culture, explore it and enjoy it",
    organiser: "Chitkara University",
    date: "WED,APR 17",
    time: "4:00 PM",
  },
  {
    id: 7,
    src: "/images/img7.jpg",
    catname: "College",
    eventname: "Youth Fest",
    location: "Delhi",
    ticketprice: 300,
    ticketsize: 2000, // for total no. of people
    likes: 0,
    description:
      "A Place to showcase your talent and enjoy fun activities and events",
    organiser: "DU",
    date: "SUN,APR 14",
    time: "9:00 AM",
  },
];

export default Events;
